openapi: 3.0.0

info:
    title: Get Device Information
    description: Runs Logic app to return device information
    version: "0.9.2"

servers:
    - url: https://example.com

paths:
    /:
        post: 
            operationId: GetDeviceInfo
            summary: Send Device Name to Logic App
            description: Invokes the logic app

            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GetDeviceInfo"
                        examples:
                            example:
                                value:
                                    DeviceName: "NZ-ABC123"

            responses:
                "200":
                    description: Send results back
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/sendData"

components:
    schemas:
        GetDeviceInfo:
            type: object
            required:
                - DeviceName
            properties:
                DeviceName:
                    type: string
                    description: Name of device to lookup

        sendData:
            type: object
            required:
                - DeviceInformation
                - DeviceAlerts
            properties:
                DeviceInformation:
                    type: object
                DeviceAlerts:
                    type: array

