openapi: 3.0.0

info:
    title: SITAv2 Run KQL Queries
    description: Runs pre-defined KQL queries to return data to be used by SITAv2 agents
    version: "1.0.0"

servers:
    - url: https://example.com

paths:
    /:
        post: 
            operationId: SITAv2InitiateEntityQueries
            summary: Initiate Pre-defined queries to return data for use by SITA agents
            description: Initiate Pre-defined queries to return data for use by SITA agents

            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SITAv2InitiateKQLQuery"

            responses:
                "200":
                    description: Send results back
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/sendResults"

components:
    schemas:
        SITAv2InitiateKQLQuery:
            type: object
            required:
                - EntityCategory
                - EntityValue
            properties:
                EntityCategory:
                    type: string
                    description: Type of entity
                EntityValue:
                    type: string
                    description: Entity value

        sendResults:
            type: object
            required:
                - Results
            properties:
                Results:
                    type: array

