openapi: 3.0.0

info:
    title: Virus Total Lookup
    description: Lookup IP Addresses using Spur US IP Context service.
    version: "0.9.2"

servers:
    - url: https://www.virustotal.com/api/v3/

paths:
    /domains/{domain}:
        get: 
            operationId: DomainLookup
            summary: Submits domain for lookup
            parameters:
                - name: domain
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Successful request
                400:
                    description: Unsuccesful request 
            
    /files/{id}:
        get:
            operationId: FileLookup
            summary: Submits file for lookup
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Successful request
                400:
                    description: Unsuccesful request 